name: ADF Medallion CD Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - adf_publish

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Publish Branch
        uses: actions/checkout@v3
        with:
          ref: adf_publish

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy ARM Template
        uses: azure/arm-deploy@v1
        with:
          # Change this line below to kavidatafact
          resourceGroupName: kavidatafact 
          template: ./kavithamas/ARMTemplateForFactory.json
          parameters: ./kavithamas/ARMTemplateParametersForFactory.json
          deploymentMode: Incremental
