name: ADF Medallion CD Pipeline

on:
  workflow_dispatch:  # Allows manual triggers from the Actions tab
  push:
    branches:
      - adf_publish  # Triggers automatically when you publish in ADF

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Publish Branch
        uses: actions/checkout@v3
        with:
          ref: adf_publish

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy ARM Template
        uses: azure/arm-deploy@v1
        with:
          resourceGroupName: rg-adf-deployment 
          template: ./kavithamas/ARMTemplateForFactory.json
          parameters: ./kavithamas/ARMTemplateParametersForFactory.json factoryName=kavithamas-medallion
          deploymentMode: Incremental
